name: jkk

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/jkk.yml"
      - "monitor.mjs"
      - "package.json"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show versions
        run: |
          node -v
          "$CHROME_PATH" --version
        env:
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}

      # lockfile がないため npm ci は使わず install を使います
      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Run monitor.mjs
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: node monitor.mjs

      - name: Upload pages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pages-${{ github.run_number }}
          path: pages
