name: jkk

on:
  workflow_dispatch:
  push:
    paths:
      - "monitor.mjs"
      - "package.json"
      - ".github/workflows/jkk.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ロックファイルが無い想定なので install を使用
      - name: Install
        run: npm install --no-audit --no-fund

      - name: Run monitor
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: node monitor.mjs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: out
          path: out/*
