name: run

on:
  workflow_dispatch:
  push:
    paths:
      - 'monitor.js'
      - '.github/workflows/jkk.yml'
      - 'package.json'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # ← cache は指定しない

      - name: Install deps
        run: npm ci || npm i   # lock があれば ci、無ければ i

      - name: Run
        run: node monitor.js

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
