name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    - cron: "12 */3 * * *"  # 任意で変更OK

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install npm deps
        run: npm install

      # 公式CLIでブラウザ本体＋必要OSパッケージをまとめて導入
      - name: Install Playwright (browsers + system deps)
        run: npx --yes playwright@latest install --with-deps chromium

      - name: Run script
        env:
          JKK_SEARCH_KANA: "コーシャハイム"
          OUT_DIR: "artifacts"
        run: |
          mkdir -p artifacts
          node monitor.mjs || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts-${{ github.run_id }}
          path: artifacts/**
          if-no-files-found: warn
          retention-days: 14
