name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    - cron: "12 */3 * * *" # 3時間ごと（任意で変更可）

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 依存とブラウザ & 必要ライブラリをまとめて導入（libasound2 の t64 問題も吸収）
      - name: Install Playwright Browsers & Deps
        uses: microsoft/playwright-github-action@v1

      - name: Install deps
        run: npm install

      - name: Run script
        env:
          JKK_SEARCH_KANA: "コーシャハイム"
          OUT_DIR: "artifacts"
        run: node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts-${{ github.run_id }}
          path: artifacts/
          if-no-files-found: warn
