name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    # GitHub Actions は 5分刻みではない “*/30 22-14 * * *” のような日跨ぎ表記を受け付けません
    # → 2本に分けて表現します（UTC 想定）
    - cron: "*/30 22-23 * * *"  # 22:00–23:59
    - cron: "*/30 0-14 * * *"   # 00:00–14:59

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm deps
        run: npm ci

      - name: Install Playwright (browsers + system deps)
        run: npx playwright install --with-deps

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts
          path: artifacts
          if-no-files-found: warn
