name: JKK scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 22-23 * * *"   # 22:00-23:59 に30分間隔
    - cron: "*/30 0-14 * * *"    # 00:00-14:59 に30分間隔

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm --yes init -y
          npm i playwright@^1
          npx playwright install --with-deps chromium

      - name: Run scraper
        run: node jkk_scrape.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jkk-output
          path: out/
          if-no-files-found: warn
