name: jkk.yml

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || true
          if ! command -v google-chrome >/dev/null; then
            sudo apt-get install -y google-chrome || true
          fi
          which google-chrome || true
          google-chrome --version || true

      - name: Install deps (puppeteer-core only)
        run: |
          npm i --no-audit --no-fund puppeteer-core@22

      - name: Run monitor
        env:
          CHROME_PATH: /usr/bin/google-chrome
        run: node monitor.mjs

      - name: Upload artifacts (out/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
          if-no-files-found: warn
