name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"   # 毎時10分に実行（必要に応じて変更OK）

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm deps
        run: npm ci

      - name: Install Playwright (browsers + system deps)
        run: npx playwright install --with-deps chromium

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
