name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    # GitHub cronはUTC。22-23時と0-14時を「2行」に分けて30分間隔で実行
    - cron: "*/30 22-23 * * *"
    - cron: "*/30 0-14 * * *"

concurrency:
  group: jkk-watch
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Tokyo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install npm deps (CI)
        run: npm ci

      - name: Install Playwright (browsers + system deps)
        run: npx playwright install --with-deps chromium

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
