name: jkk

on:
  workflow_dispatch:
  push:
    paths:
      - "monitor.mjs"
      - "package.json"
      - ".github/workflows/jkk.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Monitor
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
          BASE_URL: https://jhomes.to-kousya.or.jp
        run: npm run monitor

      - name: Upload out/**
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-watch-out
          path: out/**
