name: jkk

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # 30分ごと（必要に応じて調整）

permissions:
  contents: read

concurrency:
  group: jkk-watch
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show Chrome path
        run: |
          echo "Chrome path: ${{ steps.chrome.outputs.chrome-path }}"
          "${{ steps.chrome.outputs.chrome-path }}" --version

      - name: Install deps
        run: npm install --no-fund --no-audit

      - name: Run monitor
        env:
          # setup-chrome の出力を Puppeteer に渡す
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}

          # 参照元（ブロック回避のため最初に踏む）
          REFERER: "https://www.to-kousya.or.jp/chintai/index.html"

          # ランチャー(wait.jsp)を直接踏む
          WAIT_URL: "https://jhomes.to-kousya.or.jp/search/jkknet/wait.jsp"

          # スクショサイズ
          VIEWPORT_W: "1280"
          VIEWPORT_H: "2200"
        run: npm run monitor

      - name: Upload out/**
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-out
          path: out/**
          if-no-files-found: warn
          retention-days: 7
