name: jkk.yml
on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # lockfile が無くても毎回クリーンに入るように
      - name: Install deps
        run: |
          rm -f package-lock.json
          npm init -y >/dev/null 2>&1 || true
          # レガシー互換を保つため puppeteer-core は 10 以上ならOK。固定で22入れるが古いAPIは使わない。
          npm i puppeteer-core@22

      - name: Run monitor.mjs
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        run: node monitor.mjs

      - name: Upload out/**
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
          if-no-files-found: warn
