name: run

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Google Chrome
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | \
            sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] https://dl.google.com/linux/chrome/deb/ stable main" | \
            sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome-stable --version || true
          command -v google-chrome || true
          command -v google-chrome-stable || true
          ls -l /usr/bin/google-chrome* || true

      - name: Discover Chrome path (export to env)
        run: |
          set -eux
          BIN="$(command -v google-chrome || true)"
          if [ -z "$BIN" ]; then
            BIN="$(command -v google-chrome-stable || true)"
          fi
          if [ -z "$BIN" ]; then
            echo "Chrome binary not found on PATH" >&2
            exit 1
          fi
          echo "Found Chrome at: $BIN"
          echo "PUPPETEER_EXECUTABLE_PATH=$BIN" >> $GITHUB_ENV

      - name: Install deps
        run: npm i --no-audit --no-fund

    - name: Run monitor
      run: node monitor.mjs
      env:
        CHROME_PATH: /usr/bin/google-chrome
        JKK_KANA: コーシャハイム
        
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
