name: run

on:
  workflow_dispatch: {}
  push:
    paths:
      - "monitor.mjs"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/jkk.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Run monitor
        run: node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
