name: jkk
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # 毎時0分

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome path
        run: echo "CHROME=$CHROME" && which $CHROME
        env:
          CHROME: ${{ steps.chrome.outputs.chrome-path }}

      - name: Install deps
        run: npm i --no-audit --no-fund

      - name: Monitor
        run: npm run monitor
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-out
          path: out/**
          if-no-files-found: warn
