name: JKK Watch (smoke test)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm ci || npm i
          npx playwright install --with-deps chromium

      - name: Run node monitor.js
        run: node monitor.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: page-dump
          path: |
            *.png
            dump/**
          if-no-files-found: warn
          retention-days: 7
