name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    # 例: 平日 9:00 と 15:00 に実行（任意で調整OK）
    - cron: '0 0,6 * * 1-5'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Install Playwright (browsers + system deps)
        run: npx playwright install --with-deps

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts
          path: artifacts
          if-no-files-found: warn
