name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    # UTC 22:00-23:59（JST 07:00-08:59 相当）
    - cron: "*/30 22-23 * * *"
    # UTC 00:00-14:59（JST 09:00-23:59 相当）
    - cron: "*/30 0-14 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm deps (with lockfile)
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Lockfile missing. Run 'npm install' locally once and commit package-lock.json."; exit 1;
          fi
          npm ci

      - name: Install Playwright (browsers + system deps)
        run: npx playwright install --with-deps

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
