name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    # 毎日 08:30 JST（23:30 UTC）に回す例。お好みで調整してください
    - cron: "30 23 * * *"

permissions:
  contents: read

concurrency:
  group: jkk-watch
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      DEBUG: pw:api
      NODE_OPTIONS: --unhandled-rejections=strict
      ARTIFACT_DIR: artifacts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install npm deps
        run: |
          npm ci

      - name: Install Playwright (browsers + system deps)
        run: |
          npx playwright install --with-deps chromium

      - name: Run script
        run: |
          mkdir -p "$ARTIFACT_DIR"
          node monitor.mjs

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts
          path: |
            artifacts/**
            debug.log
            *.html
            *.png
            trace.zip
          if-no-files-found: ignore
