# .github/workflows/jkk.yml
name: run
on: { workflow_dispatch: {} }

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"   # ← cache は指定しない

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Resolve Chrome path
        shell: bash
        run: |
          set -eo pipefail
          CHROME_BIN="${{ steps.chrome.outputs.chrome-path }}"
          if [ -n "$CHROME_BIN" ] && [ ! -x "$CHROME_BIN" ]; then
            CHROME_BIN="$(command -v "$CHROME_BIN" || true)"
          fi
          [ -z "$CHROME_BIN" ] && CHROME_BIN="$(command -v google-chrome || true)"
          [ -z "$CHROME_BIN" ] && CHROME_BIN="$(command -v google-chrome-stable || true)"
          [ -z "$CHROME_BIN" ] && CHROME_BIN="$(command -v chromium || true)"
          [ -z "$CHROME_BIN" ] && CHROME_BIN="$(command -v chromium-browser || true)"
          echo "Using CHROME_PATH=$CHROME_BIN"
          test -x "$CHROME_BIN"
          echo "CHROME_PATH=$CHROME_BIN" >> $GITHUB_ENV

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Run
        run: node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
