name: jkk-kosha-search

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: 'フリーワード（未指定なら「コーシャハイム」）'
        required: false
        default: 'コーシャハイム'

permissions:
  contents: read

concurrency:
  group: jkk-kosha-search
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci || npm install
          npx playwright install --with-deps chromium

      - name: Run kosha search
        env:
          CI: "true"
          JKK_KEYWORD: ${{ github.event.inputs.keyword || 'コーシャハイム' }}
        run: node jkk_search_kosha.mjs

      - name: Upload artifacts (out/)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-out-${{ github.run_id }}
          path: |
            out/**
          if-no-files-found: warn
          retention-days: 14
