name: jkk

on:
  workflow_dispatch:
    inputs:
      kana:
        description: "住宅名（カナ）に入れる語（例：コーシャハイム あるいは ｺｰｼｬﾊｲﾑ）"
        required: false
        default: "コーシャハイム"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # ※ロックファイル無しでOKにするため cache は使わない

      - name: Install npm deps
        run: npm install

      - name: Install Playwright (browsers + system deps)
        run: npx playwright install --with-deps chromium

      - name: Run script
        env:
          SEARCH_KANA: ${{ github.event.inputs.kana }}
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jkk-${{ github.run_number }}
          path: artifacts
          if-no-files-found: warn
