name: jkk

on:
  workflow_dispatch:
  push:
    paths:
      - 'monitor.mjs'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/jkk.yml'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          npm ci --no-audit --no-fund

      - name: Install Playwright (browsers + system deps)
        run: |
          npx playwright install --with-deps

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jkk-artifacts
          path: |
            artifacts/**
            *.png
            *.html
            *.log
          if-no-files-found: warn
