name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"  # 毎日09:30JST くらい

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'   # ← package-lock.json が必須。なければこの行を消す

      - name: Install deps
        run: |
          npm ci --no-audit --no-fund
          npm run install:pw

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs
        env:
          CI: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts/
          if-no-files-found: ignore
