name: run

on:
  workflow_dispatch:

concurrency:
  group: jkk-watch
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # lockfile が無ければここで作る
      - name: Ensure lockfile
        run: |
          if [ ! -f package-lock.json ]; then
            echo "package-lock.json が無いので生成します"
            npm i --package-lock-only --no-audit --no-fund
          fi

      - name: Install deps
        run: npm ci --no-audit --no-fund

      # monitor.mjs / monitor.js のどちらかを自動検出
      - name: Pick entry script
        run: |
          set -e
          if [ -f monitor.mjs ]; then
            echo "ENTRY=monitor.mjs" >> $GITHUB_ENV
            echo "Found monitor.mjs"
          elif [ -f monitor.js ]; then
            echo "ENTRY=monitor.js" >> $GITHUB_ENV
            echo "Found monitor.js"
          else
            echo "✗ monitor.mjs / monitor.js が見つかりません。カレント:"
            pwd
            ls -la
            exit 1
          fi

      - name: Run monitor
        run: node "$ENTRY"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out/**
          if-no-files-found: warn
