name: jkk.yml

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 0 * * 1-5"

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      # ← ここを npm ci ではなく npm install に変更
      - name: Install deps (no chromium download)
        run: npm install --ignore-scripts --no-audit --no-fund

      - name: Run monitor
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
          BASE_URL: https://jhomes.to-kousya.or.jp
          KANA: ""
          WIDTH: "1440"
          HEIGHT: "2200"
        run: npm run monitor

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jkk-out
          path: out/**
          if-no-files-found: warn
