name: jkk-watch

on:
  workflow_dispatch:
  schedule:
    # JST 07:00–23:59 を2回/時（00分,30分）で回す
    # UTCに直すと 22–23時, 00–14時（0,30分）
    - cron: '0,30 22-23,0-14 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright (browsers + system deps)
        run: |
          npm ci || npm i
          npx playwright install --with-deps

      - name: Run script
        run: |
          mkdir -p artifacts
          node monitor.mjs

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
          retention-days: 7
